dist: xenial
language: php

env:
  global:
    - SETUP=stable

matrix:
  fast_finish: true
  include:
    - php: 7.2
    - php: 7.2
      env: SETUP=lowest
    - php: 7.3
    - php: 7.3
      env: SETUP=lowest
    - php: nightly
    - php: nightly
      env: SETUP=lowest

cache:
  directories:
    - $HOME/.composer/cache

services:
  - mysql

before_install:
  - phpenv config-rm xdebug.ini || true
  - travis_retry composer self-update
  - mysql -e 'CREATE DATABASE forge;'

install:
  - if [[ $SETUP = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest --ignore-platform-reqs; fi
  - if [[ $SETUP = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable --no-suggest --ignore-platform-reqs; fi

script: vendor/bin/phpunit
